- name: play1
  hosts: all
  tasks:
    - name: Print Hello from play1 of task1
      ansible.builtin.debug:
        msg: Hello from task1 of play1

    - name: Print Hello from play1 of task2
      ansible.builtin.debug:
        msg: Hello from task2 of play2