- name: play1
  hosts: all
  tasks:
    - name: Print Hello from play1 of task1
      ansible.builtin.debug:
        msg: Hello from task1 of play1

    - name: Print Hello from play1 of task2
      ansible.builtin.debug:
        msg: Hello from task2 of play2

- name: play2
  hosts: dev
  tasks:
    - name: Print Hello from play2 of task1
      ansible.builtin.debug:
        msg: Hello from task1 of play2