- name: play1
  hosts: all
  vars:
    URL: play.google.com
  tasks:
    - name: Printing the URL Task
      ansible.builtin.debug:
        msg: the value of URL is {{URL}}

    - name: Printing the URL Task
      ansible.builtin.debug:
        msg: the value of URL is {{URL}}
      vars:
        URL: Task.google.com