- name: play1
  hosts: all
  vars:
    URL: play.google.com
  vars_files: demo-vars.yaml
  vars_prompt:
    - name: NURL
      prompt: Enter the nurl
      private: false

  tasks:
    - name: Printing the URL Task
      ansible.builtin.debug:
        msg: the value of URL is {{URL}}

    - name: Printing the URL Task
      ansible.builtin.debug:
        msg: the value of URL is {{URL}}
      vars:
        URL: Task.google.com

    - name: Printing the URL Task
      ansible.builtin.debug:
        msg: "{{URL}}"
      vars:
        URL: Task.google.com

    - name: Printing the value from cmd line
      ansible.builtin.debug:
        msg: "{{CMD_URL}}"

    - name: Printing the value from files
      ansible.builtin.debug:
        msg: "{{game_lives}}"

    - name: Printing the prompt URL
      ansible.builtin.debug:
        msg: "{{name}}"