- name: Configuring the Erlang repo
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | sudo bash

- name: Configuring the rabbitmq
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | sudo bash

- name: Install rabbitmq-server
  ansible.builtin.package:
    name: rabbitmq-server
    state: present

- name: Enable service rabbitmq
  ansible.builtin.service:
    name: rabbitmq-server
    state: started
    enabled: yes

- name: Creating rabbitmq application user
  community.rabbitmq.rabbitmq_user:
    user: roboshop
    password: roboshop123
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present
