- name: Performing cleanup
  ansible.builtin.file:
    path: /home/{{APPUSER}}/{{COMPONENT}}/
    state: absent
  ignore_errors: yes

- name: Creating the component home directory
  ansible.builtin.file:
    path: /home/{{APPUSER}}/{{COMPONENT}}/
    state: directory
    mode: '0755'
  become_user: "{{APPUSER}}"

- name: Download and extract from Nexus
  ansible.builtin.unarchive:
    src: http://172.31.13.151:8081/repository/{{COMPONENT}}/{{COMPONENT}}-{{VERSION}}.zip
    dest: /home/{{APPUSER}}/{{COMPONENT}}/
    remote_src: yes
  become_user: "{{APPUSER}}"

# - name: Download and extract
#   ansible.builtin.unarchive:
#     src: https://github.com/stans-robot-project/{{COMPONENT}}/archive/main.zip
#     dest: /tmp
#     remote_src: yes

# - name: Performing cleanup
#   ansible.builtin.file:
#     path: /home/{{APPUSER}}/{{COMPONENT}}/
#     state: absent

# - name: Copying files
#   ansible.builtin.copy:
#     src: /tmp/{{COMPONENT}}-main/
#     dest: /home/{{APPUSER}}/{{COMPONENT}}/
#     owner: "{{APPUSER}}"
#     group: "{{APPUSER}}"
#     remote_src: yes