- name: Configuring the nodejs
  ansible.builtin.shell: dnf module disable nodejs -y && dnf module enable nodejs:18 -y && dnf install nodejs -y

- name: Calling create user role from common
  ansible.builtin.include_role:
    name: common
    tasks_from: create-user

- name: Calling download and extract role from common
  ansible.builtin.include_role:
    name: common
    tasks_from: download

- name: Doing npm install
  community.general.npm:
    path: /home/{{APPUSER}}/{{COMPONENT}}

- name: Calling config service role from common
  ansible.builtin.include_role:
    name: common
    tasks_from: config-svc