- name: Install Python dependencies
  ansible.builtin.yum:
    name:
      - python36
      - gcc
      - python3-devel
    state: present

- name: Calling create user role from common
  ansible.builtin.include_role:
    name: common
    tasks_from: create-user

# - name: Calling download and extract role from common
#   ansible.builtin.include_role:
#     name: common
#     tasks_from: download

- name: Calling download and extract role from common
  ansible.builtin.include_role:
    name: common
    tasks_from: download-from-nexus

- name: Fetch the UID and replace it in the file
  ansible.builtin.lineinfile:
    path: /home/{{APPUSER}}/{{COMPONENT}}/{{COMPONENT}}.ini
    regexp: '^uid'
    line: uid = {{APPUSERINFO.uid}}

- name: Fetch the UID and replace it in the file
  ansible.builtin.lineinfile:
    path: /home/{{APPUSER}}/{{COMPONENT}}/{{COMPONENT}}.ini
    regexp: '^gid'
    line: uid = {{APPUSERINFO.group}}

- name: Install application dependencies
  ansible.builtin.pip:
    requirements: /home/{{APPUSER}}/{{COMPONENT}}/requirements.txt
    executable: pip3

- name: Calling config-svc task from common
  ansible.builtin.include_role:
    name: common
    tasks_from: config-svc